
name: Satis Build

on: 
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  builder:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: dev-this/satis-build@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - env:
          git_email: buckhambot[bot]@users.noreply.github.com
          git_name: BuckhamBot
        run: |
          git checkout gh-pages
          rm -rf include/*
          cp -R build/* .
          rm -rf build/
          git config user.name $git_name
          git config user.email $git_email
          git add .
          git commit -m "Updated repository"
          git push
